version: '3'
services:
  nginx:
    image: nginx:1.25.4
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - FRONTEND_URL
      - BACKEND_URL
    command: /bin/bash -c "envsubst '$$FRONTEND_PORT $$BACKEND_PORT $$PROXY_PORT $$ORIGIN_HEADER' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
